Student_collaboration/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main"))
    
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.landingPage, name="landing"),
    path("home/", views.home, name="home"),
    path("whiteboard/<str:id>", views.whiteboard, name="whiteboard"),
    path("login/", views.loginPage, name="login"),
    path("register/", views.registerPage, name="register"),
    path("logout/", views.logoutPage, name="logout"),
    path("profile/<pk>", views.profilePage, name="profile"),
    path("edit_profile/", views.editProfilePage, name="edit_profile"),
]

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% block style %}
    {% endblock style %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock script %}

    {% include "navbar.html" %}
    
</head>
{% block body %}
{% endblock body %}
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
	<div class="container-fluid">
		<a class="navbar-brand" href="{% url "main:home" %}">The WhiteBoard</a>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarNavDropdown"
			aria-controls="navbarNavDropdown"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNavDropdown">
			<ul class="navbar-nav">
                {% if user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url "main:home" %}"
						>Home</a
					>
				</li>
				<li class="nav-item">
                    <a class="nav-link" href="{% url "main:profile" user.pk %}">Profile</a>
				</li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:logout" %}">Logout</a>
				</li>

                {% else %}
				<li class="nav-item">
                    <a class="nav-link" href="{% url "main:login" %}">Login</a>
				</li>
				<li class="nav-item">
                    <a class="nav-link" href="{% url "main:register" %}">Register</a>
				</li>
                {% endif %}

				{% comment %} <li class="nav-item dropdown">
					<a
						class="nav-link dropdown-toggle"
						href="#"
						role="button"
						data-bs-toggle="dropdown"
						aria-expanded="false"
					>
						Dropdown link
					</a>
					<ul class="dropdown-menu">
						<li><a class="dropdown-item" href="#">Action</a></li>
						<li>
							<a class="dropdown-item" href="#">Another action</a>
						</li>
						<li>
							<a class="dropdown-item" href="#"
								>Something else here</a
							>
						</li>
					</ul>
				</li> {% endcomment %}
			</ul>
		</div>
	</div>
</nav>