Student_collaboration/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main"))
    
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.landingPage, name="landing"),
    path("home/", views.home, name="home"),
    path("whiteboard/<str:id>", views.whiteboard, name="whiteboard"),
    path("login/", views.loginPage, name="login"),
    path("register/", views.registerPage, name="register"),
    path("logout/", views.logoutPage, name="logout"),
    path("profile/<pk>", views.profilePage, name="profile"),
    path("edit_profile/", views.editProfilePage, name="edit_profile"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django_mysql.models.fields.lists import ListCharField
import uuid

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = RichTextField(default="No About...")
    avatar = models.ImageField(upload_to="avatars", default="no_picture.png")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username.capitalize()

class Board(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    online_users = ListCharField(
        base_field=models.CharField(max_length=16, default=""),
        size=255,
        max_length=(255 * 17),
        default="",
    )  # type: ignore

    def to_json(self):
        return {
            "objects": [obj.to_json() for obj in self.board_objects.all()],  # type: ignore
            "online_users": [
                User.objects.get(pk=user_pk).username for user_pk in self.online_users
            ],
        }

    def get_online_users(self):
        return {
            "online_users": [
                User.objects.get(pk=user_pk).username for user_pk in self.online_users
            ],
        }

    def __str__(self):
        return str(self.id)


class BoardObject(models.Model):
    class BoardObjectType(models.TextChoices):
        path = "path"

    board = models.ForeignKey(
        Board, on_delete=models.CASCADE, related_name="board_objects"
    )
    type = models.CharField(choices=BoardObjectType.choices, max_length=16)
    data = models.JSONField(default=dict)

    def to_json(self):
        type = str(self.type)
        return {"type": type, "points": self.data["points"]}

    @classmethod
    def from_json(cls, board_id, object_data):
        board = Board.objects.get(id=board_id)
        object_data = {**object_data}

        return cls(
            board=board,
            type=object_data.pop("type"),
            data=object_data,
        )

    def __str__(self):
        return self.type + " - " + str(self.board.id)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class GenerateWhiteboardForm(forms.Form):
    pass

class DeleteCurrentWhiteboardForm(forms.Form):
    pass

class LoginForm(forms.Form):
    username = forms.CharField(max_length=120)
    password = forms.CharField(max_length=16, widget=forms.PasswordInput)

class RegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields = ('username','email' ,'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["about"]

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)

    def save(self, commit=True, *args, **kwargs):
        instance = super(EditProfileForm, self).save(commit=False, *args, **kwargs)
        return instance.save() if commit else instance

main/views.py
from django.shortcuts import render, redirect
from .forms import (
    GenerateWhiteboardForm,
    DeleteCurrentWhiteboardForm,
    LoginForm,
    RegisterForm,
    EditProfileForm,
)
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Board, Profile



def landingPage(request):
    return render(request,"landing.html")


def loginPage(request):
    if request.user.is_authenticated:
        return redirect("main:home")

    if request.method == "POST":
        username = request.POST.get("username").lower()
        password = request.POST.get("password")
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "User does not exist.")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("main:home")
        else:
            messages.error(request, "Username or Password is incorrect.")

    login_form = LoginForm()
    context = {"login_form": login_form}
    return render(request, "login.html", context=context)


def registerPage(request):
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user = register_form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            user_profile = Profile(user=user)
            user_profile.save()
            login(request, user)
            return redirect("main:home")
        else:
            messages.error(request, "An error occurred while registration process.")
            
    register_form = RegisterForm()
    context = {"register_form":register_form}
    return render(request, "register.html", context=context)


@login_required(login_url="main:login")
def logoutPage(request):
    logout(request)
    return redirect("main:login")


@login_required(login_url='main:login')
def profilePage(request, pk):
    profile = Profile.objects.get(user=User.objects.get(pk=pk))
    context = {"profile": profile}
    return render(request, "profile.html", context=context)


@login_required(login_url='main:login')
def editProfilePage(request):
    profile = Profile.objects.get(user=request.user)
    edit_profile_form = EditProfileForm(instance=profile)
    if request.method == "POST":
        edit_profile_form = EditProfileForm(request.POST)
        if edit_profile_form.is_valid():
            new_profile = edit_profile_form.save(commit=False)
            profile.about = new_profile.about
            profile.save()
            return redirect("main:profile", profile.pk)

    context = {
        "profile": profile,
        "edit_profile_form": edit_profile_form,
    }

    return render(
        request,
        "edit_profile.html",
        context=context,
    )


@login_required(login_url="main:login")
def home(request):
    generate_whiteboard_form = GenerateWhiteboardForm()
    generated_whiteboard_url: str = ""
    if request.method == "POST":
        generate_whiteboard_form = GenerateWhiteboardForm(request.POST)
        if generate_whiteboard_form.is_valid():
            board = Board.objects.create(host=request.user)
            url = reverse("main:whiteboard", kwargs={"id": board.id})
            generated_whiteboard_url = request.build_absolute_uri(url)
    context = {
        "generate_whiteboard_form": generate_whiteboard_form,
        "generated_whiteboard_url": generated_whiteboard_url,
    }

    return render(request, "home.html", context=context)


@login_required(login_url="main:login")
def whiteboard(request, id):
    delete_form = DeleteCurrentWhiteboardForm()
    try:
        board = Board.objects.get(id=id)
        if request.method == "POST":
            delete_form = DeleteCurrentWhiteboardForm(request.POST)
            if delete_form.is_valid():
                board.delete()
                return redirect("main:home")

    except Exception as e:
        print("Error:- ", e)
        return redirect("main:home")

    context = {
        "board_id": id,
        "host_pk": board.host.pk,
        "delete_form": delete_form,
    }
    return render(request, "whiteboard.html", context=context)

main/templates/main/edit_profile.html
{% extends "index.html" %}
{% load static %}

{% block body %}
<main class="mb-4">
	<div class="container px-4 px-lg-5">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10 col-lg-8 col-xl-7">
                <form method="POST">
                    {% csrf_token %}
                    {{edit_profile_form.media}}
                    {{edit_profile_form.as_p}}
                    <input type="submit">
                </form>
            </div>
		</div>
	</div>
</main>
{% endblock body %}


main/templates/main/home.html
{% extends "index.html" %} 
{% block body %}
<body>
	<form id="whiteboard_form" method="POST">
		{% csrf_token %} 
        {{ generate_whiteboard_form.as_p }}
		<input type="submit" value="Generate" />
	</form>

	{% if generated_whiteboard_url %}
	<a href="{{generated_whiteboard_url}}">{{generated_whiteboard_url}}</a>
	{% endif %}
</body>
{% endblock body %}

main/templates/main/landing.html
{% extends "index.html" %}
{% load static %}


{% block body %}

<br>
<a href="{% url "main:login" %}">
    <button type="button" class="btn btn-primary">Login</button>
</a>

<br>
<br>

<a href="{% url "main:register" %}">
    <button type="button" class="btn btn-primary">Register</button>
</a>
{% endblock body %}

main/templates/main/login.html
{% extends "index.html" %}
{% load static %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    {{login_form.as_p}}
    <input type="submit" value="Login">
</form>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<p>If not registered then <a href="{% url "main:register" %}">register</a>. </p>

{% endblock body %}

main/templates/main/profile.html
{% extends "index.html" %}
{% load static %}

{% block body %}
<main class="mb-4">
	<div class="container px-4 px-lg-5">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10 col-lg-8 col-xl-7">
                {{profile.about | safe}}
            </div>
			<div class="d-flex justify-content-end mb-4">
				{% if profile.user.id == user.id %}
				<a
					class="btn btn-primary float-right"
					href="{% url 'main:edit_profile' %}"
					>Edit Profile</a
				>
				{% endif %}
			</div>
		</div>
	</div>
</main>
{% endblock body %}

main/templates/main/register.html
{% extends "index.html" %}
{% load static %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    {{register_form.as_p}}
    <input type="submit" value="Register">
</form>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<p>If Already registered then <a href="{% url "main:login" %}">login</a>. </p>

{% endblock body %}

main/templates/main/whiteboard.html
{% extends "index.html" %} 
{% load static %}

{% block body %}
<body style="background-color: #f1f1f1">
    <canvas id="whiteboard" style= "background-color: white;"></canvas>

    <script>
        window.boardID = "{{board_id}}";
        
        var canvas = document.getElementById("whiteboard");

        canvas.height = window.innerHeight - 150;
        canvas.width = window.innerWidth;
        
    </script>

    <script src="{% static 'web/index.js' %}" ></script>
    <p>Online:- <span id="show_users_count">hi</span></p>
    
    {% if user.pk == host_pk %}
        <form method="POST">
            {% csrf_token %}
            {{delete_form.as_p}}
            <input type="submit" value="Delete">
        </form>
    {% endif %}

</body>
{% endblock body %}